In [2]:
import numpy as np

In [5]:
a1 = np.arange(8).reshape(2,4)
a2 = np.arange(8, 16).reshape(2, 4)
print(a1)
print(a2)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [6]:
a1 + a2

array([[ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [7]:
a3 = np.arange(9).reshape(3, 3)
a4 = np.arange(3).reshape(1, 3)
print(a3)
print(a4)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2]]


broadcasting: adding two array no different shapes

In [8]:
a3+a4

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10]])

In [ ]:
a5 = np.arange(3).reshape(1, 3)
a6 = np.arange(12).reshape(4,3)
print(a5)
print(a6)

[[0 1 2]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [10]:
a5 + a6

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10],
       [ 9, 11, 13]])

In [12]:
a7 = np.arange(4).reshape(1, 4)
a8 = np.arange(12).reshape(3, 4)
print(a7)
print(a8)

[[0 1 2 3]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [13]:
a7 + a8

array([[ 0,  2,  4,  6],
       [ 4,  6,  8, 10],
       [ 8, 10, 12, 14]])

In [14]:
a11 = np.arange(3).reshape(1, 3)
a12 = np.arange(3).reshape(3,1)
print(a11)
print(a12)

[[0 1 2]]
[[0]
 [1]
 [2]]


In [15]:
a11 + a12

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [16]:
a13 = np.arange(1).reshape(1,1)
a14 = np.arange(20).reshape(4,5)
print(a13)
print(a14)

[[0]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [17]:
a13 + a14

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [20]:
a15 =np.arange(4)
a16 = np.arange(20).reshape(5,4)
print(a15)
print(a16)

[0 1 2 3]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [19]:
a15 + a16

array([[ 0,  2,  4,  6],
       [ 4,  6,  8, 10],
       [ 8, 10, 12, 14],
       [12, 14, 16, 18],
       [16, 18, 20, 22]])