In [1]:
import numpy as np

In [2]:
np.random.random()

0.03189395645033566

constant random value

In [5]:
np.random.seed(1)
np.random.random()

0.417022004702574

random value between two number

In [11]:
np.random.uniform(3, 10)

4.303821479643696

10 random value 1 to 100

In [13]:
np.random.uniform(1, 100, 10).reshape(5,2)

array([[56.31029302, 14.89830692],
       [20.61204742, 80.2737123 ],
       [96.857896  , 32.02899364],
       [69.53993895, 87.76252608],
       [89.56605969,  9.41937693]])

integer

In [21]:
np.random.randint(1, 10, 6).reshape(3,2)

array([[5, 3],
       [8, 8],
       [9, 7]], dtype=int32)

In [33]:
a = np.random.randint(1, 10, 6)
a

array([5, 6, 7, 3, 6, 8], dtype=int32)

In [34]:
np.max(a)

np.int32(8)

In [35]:
np.min(a)

np.int32(3)

In [39]:
np.argmax(a)

np.int64(5)

In [38]:
np.argmin(a)

np.int64(3)

In [36]:
a[np.argmax(a)]

np.int32(8)

In [37]:
a[np.argmin(a)]

np.int32(3)

modify value: if odd then value gets -1 else no change

In [40]:
a[a%2==1]=-1
a

array([-1,  6, -1, -1,  6,  8], dtype=int32)

In [42]:
a = np.random.randint(1, 50, 6)
a

array([40,  8, 46,  5, 49, 19], dtype=int32)

not modify value: if odd then value gets -1 else no change

In [ ]:
np.where(a%2==1, -1, a)


array([40,  8, 46, -1, -1, -1], dtype=int32)

In [44]:
a

array([40,  8, 46,  5, 49, 19], dtype=int32)

In [46]:
a = np.random.randint(1, 50, 10)
a

array([33, 13,  2, 31, 42, 25, 19, 34,  3, 45], dtype=int32)

In [48]:
a=np.sort(a)
a

array([ 2,  3, 13, 19, 25, 31, 33, 34, 42, 45], dtype=int32)

In [49]:
np.percentile(a, 25)

np.float64(14.5)

In [50]:
np.percentile(a, 50)

np.float64(28.0)

In [52]:
np.percentile(a, 98)

np.float64(44.46)