In [43]:
import numpy as np # type: ignore

In [44]:
arr1 =np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [45]:
type(arr1)

numpy.ndarray

In [46]:
arr2 =np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [47]:
arr3 = np.zeros((2,3))
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [48]:
arr4 = np.ones((3,3))
arr4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [49]:
arr5 = np.identity(4)
arr5

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

its same like renge but its return array, renge return tuple 

In [50]:
arr6 =np.arange(5,16,2)
arr6

array([ 5,  7,  9, 11, 13, 15])

between 10 to 20 linspace giving 10 number

In [51]:
arr7=np.linspace(10, 20, 10)
arr7

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [52]:
arr8=arr7.copy()
arr8

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [53]:
arr1.shape

(5,)

In [54]:
arr2.shape

(2, 3)

In [55]:
arr9 = np.array([[[1,2],[3,4]], [[5,6], [7,8]]])
arr9

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [56]:
arr9.shape

(2, 2, 2)

In [57]:
arr9.ndim

3

In [58]:
arr2.ndim

2

In [59]:
arr1.ndim

1

In [60]:
arr1

array([1, 2, 3, 4, 5])

Size means number of items

In [61]:
arr1.size

5

In [62]:
arr9

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [63]:
arr9.size

8

In [68]:
arr1.itemsize

8

In [65]:
arr9.itemsize

8

In [67]:
arr8.itemsize

8

to see the type

In [69]:
arr8.dtype

dtype('float64')

to change the type

In [70]:
arr9.dtype

dtype('int64')

In [71]:
arr9.astype('float')

array([[[1., 2.],
        [3., 4.]],

       [[5., 6.],
        [7., 8.]]])

In [72]:
arr7

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [73]:
arr7.astype('int')

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 20])