In [23]:
import numpy as np

In [24]:
arr1 =np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [25]:
arr1[3]

np.int64(4)

In [26]:
arr1[2:4]

array([3, 4])

In [27]:
arr1[-1]

np.int64(5)

In [28]:
arr12 = np.arange(24).reshape(6, 4)
arr12

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [29]:
arr12[2]

array([ 8,  9, 10, 11])

print column arr12[row-start : row-end : row-step, column-start : column-end: column-step ]

In [30]:
arr12[:,1:3]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14],
       [17, 18],
       [21, 22]])

In [31]:
array13 = arr12[:,1:3]
array13[2:4]

array([[ 9, 10],
       [13, 14]])

In [34]:
arr12[2:4,1:3]

array([[ 9, 10],
       [13, 14]])

In [36]:
arr12[4:6, 2:4]

array([[18, 19],
       [22, 23]])

In [37]:
for i in arr12:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
[16 17 18 19]
[20 21 22 23]


In [39]:
for i in np.nditer(arr12):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
