In [1]:
import numpy as np

In [5]:
arr = np.random.randint(low=1, high=100, size=20).reshape(4,5)
arr

array([[39, 35, 36, 57, 89],
       [53, 70, 56, 94, 85],
       [64, 95, 46, 16, 64],
       [71, 10, 56, 73, 56]], dtype=int32)

In [8]:
arr>50

array([[False, False, False,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True, False, False,  True],
       [ True, False,  True,  True,  True]])

indexing using boolean array

In [9]:
arr[arr>50]

array([57, 89, 53, 70, 56, 94, 85, 64, 95, 64, 71, 56, 73, 56],
      dtype=int32)

In [12]:
arr[(arr>50) & (arr%2!=0)]

array([57, 89, 53, 85, 95, 71, 73], dtype=int32)

In [14]:
arr[(arr>50) & (arr%2!=0)]=0
arr

array([[39, 35, 36,  0,  0],
       [ 0, 70, 56, 94,  0],
       [64,  0, 46, 16, 64],
       [ 0, 10, 56,  0, 56]], dtype=int32)